version: '3.8'

services:
  taskbox:
    image: l1apps/taskbox:latest
    container_name: taskbox
    ports:
      - "6500:3000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      # It is strongly recommended to change this to a long, random string for security
      - JWT_SECRET=your-super-secret-key-that-should-be-in-an-env-file